name: Deploy static Portfolio to GitHub Pages

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [main]
    workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4